#!/bin/bash

# mix test.watch does not use the tmux notifier since I switch to an umbrella design.

function color_pane() {
    COLOR=$1 # "green" or "red"
    tmux set-window-option -t"$TMUX_PANE" window-status-style bg=$COLOR
}

export -f color_pane
exec rg --files | entr bash -c "mix test && color_pane green || color_pane red"
